using System;

namespace GasGiantNet.Random
{
    // todo: remove after ensure "good enough" results on System.Random()
    internal static class NumpyDistributions
    {
        // The bit generator itself is bit-compatible with NumPy. Distribution
        // transforms are isolated here. The exact NumPy Ziggurat tables are
        // generated by tools/generate_numpy_tables.py into NumpyZigguratTables.cs.
        public static double StandardNormal(NumpyGenerator rng)
        {
            if (!NumpyZigguratTables.Enabled)
                throw new InvalidOperationException("NumPy Ziggurat tables are required for parity.");
            return ZigguratNormal(rng);
        }

        private static double ZigguratNormal(NumpyGenerator rng)
        {
            for (;;)
            {
                ulong r = rng.NextUInt64();
                int idx = (int)(r & 0xffUL);
                r >>= 8;
                int sign = (int)(r & 1UL);
                ulong rabs = (r >> 1) & 0x000fffffffffffffUL;
                double x = rabs * NumpyZigguratTables.WiDouble[idx];
                if ((sign & 1) != 0) x = -x;
                if (rabs < NumpyZigguratTables.KiDouble[idx]) return x;
                if (idx == 0)
                {
                    for (;;)
                    {
                        double xx = -NumpyZigguratTables.NorInvR * Log1p(-rng.Random());
                        double yy = -Log1p(-rng.Random());
                        if (yy + yy > xx * xx)
                            return (((rabs >> 8) & 1UL) != 0) ? -(NumpyZigguratTables.NorR + xx) : NumpyZigguratTables.NorR + xx;
                    }
                }
                if (((NumpyZigguratTables.FiDouble[idx - 1] - NumpyZigguratTables.FiDouble[idx]) * rng.Random()
                    + NumpyZigguratTables.FiDouble[idx]) < Math.Exp(-0.5 * x * x)) return x;
            }
        }

        private static double Log1p(double x)
        {
            // Portable log1p for C#/.NET: retain precision near zero, where
            // Math.Log(1+x) loses low bits. This matches the mathematical
            // transform used by NumPy's Ziggurat tail closely enough to be
            // parity-tested by NumpyParitySelfTest.
            double ax = Math.Abs(x);
            if (ax > 1.0e-4) return Math.Log(1.0 + x);
            double term = x;
            double sum = 0.0;
            for (int n = 1; n <= 18; n++)
            {
                double add = term / n;
                sum += (n & 1) == 1 ? add : -add;
                term *= x;
            }
            return sum;
        }

        public static long Poisson(NumpyGenerator rng, double lam)
        {
            if (lam < 0.0 || double.IsNaN(lam)) throw new ArgumentException("lambda must be nonnegative");
            if (lam == 0.0) return 0;
            if (lam >= 10.0) return PoissonPtrs(rng, lam);
            double enlam = Math.Exp(-lam);
            long x = 0;
            double prod = 1.0;
            for (;;)
            {
                prod *= rng.Random();
                if (prod > enlam) x++;
                else return x;
            }
        }

        // Hoermann transformed-rejection algorithm used by NumPy for lam >= 10.
        private static long PoissonPtrs(NumpyGenerator rng, double lam)
        {
            double slam = Math.Sqrt(lam);
            double loglam = Math.Log(lam);
            double b = 0.931 + 2.53 * slam;
            double a = -0.059 + 0.02483 * b;
            double invalpha = 1.1239 + 1.1328 / (b - 3.4);
            double vr = 0.9277 - 3.6224 / (b - 2.0);
            for (;;)
            {
                double u = rng.Random() - 0.5;
                double v = rng.Random();
                double us = 0.5 - Math.Abs(u);
                long k = (long)Math.Floor((2.0 * a / us + b) * u + lam + 0.43);
                if (us >= 0.07 && v <= vr) return k;
                if (k < 0 || (us < 0.013 && v > us)) continue;
                if (Math.Log(v * invalpha / (a / (us * us) + b)) <= -lam + k * loglam - LogFactorial(k)) return k;
            }
        }

        private static double LogFactorial(long k)
        {
            // Host-side Poisson lambdas in gas-giant are modest. Exact integer
            // summation matches lgamma closely and avoids an external special-function dependency.
            if (k < 2) return 0.0;
            double s = 0.0;
            for (long i = 2; i <= k; i++) s += Math.Log(i);
            return s;
        }
    }

}
